version: "3.8"

# volumes:
#     vol-emqx-data:
#       name: foo-emqx-data
#     vol-emqx-etc:
#       name: foo-emqx-etc
#     vol-emqx-log:
#       name: foo-emqx-log

services:
    mongo:
      container_name: mongo
      image: mongo:4.4
      restart: always
      environment: 
        TZ: "America/Mexico/Mexico_City"
        MONGO_INITDB_ROOT_USERNAME: "devuser"
        MONGO_INITDB_ROOT_PASSWORD: "devpassword"
      volumes: 
        - ./mongodata:/data/db 
      ports: 
        - 27017:27017

    emqx:
        container_name: emqx
        image: emqx/emqx:4.2.3
        restart: always
        ports:
            - 18083:18083
            - 8083:8083
        
        # volumes:
            
        #     - vol-emqx-data:/opt/emqx/data
        #     - vol-emqx-etc:/opt/emqx/etc
        #     - vol-emqx-log:/opt/emqx/log

        links: 
          - mongo


        environment: 

            EMQX_NAME: iot-ihs
            EMQX_HOST: 127.0.0.1

            TZ: "America/Mexico/Mexico_City"

            #Desafult dash pass
            #dashboard.default_user.login=admin
            EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "1234"

            #Mongo Connection
            # MONGO CONNECTION
            EMQX_AUTH__MONGO__TYPE: single
            EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
            EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

            EMQX_AUTH__MONGO__SERVER: "mongo:27017"
            EMQX_AUTH__MONGO__POOL: 8

            EMQX_AUTH__MONGO__LOGIN: "devuser"
            EMQX_AUTH__MONGO__PASSWORD: "devpassword"
            EMQX_AUTH__MONGO__AUTH_SOURCE: admin

            EMQX_AUTH__MONGO__DATABASE: "iotihs"
            EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

            EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
            EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
            EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
            EMQX_AUTH__MONGO__SUPER_QUERY: "off"

            EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
            EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
            EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
            




            EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
        